export interface IUser {
  entrNo: string,
  mbrStusCd: string,
  cucoNm: string,
  brno: string | null,
  svcNm: string,
  svcCd: string,
  entrStusCd: string,
  entrStusNm: string,
  sbscUpldSped: string,
  sbscDownSped: string,
  agmtTermYyct: string,
  cntcStrtDt: string,
  cntcEndDt: string,
  cucoChrrNm: string,
  cucoChrrHpno: string,
  cucoEmalAddr: string,
  lastLoginDttm: string | null,
}

export interface IServiceData {
  entrNo: string,
  trfEvetOccrDttm: string,
  svcNm: string,
  cucoNm: string,
  cntcStrtDt: string,
  sbscUpldSped: string,
  sbscDownSped: string,
  occrTrfUpldSpedVlue: string,
  occrTrfDownSpedVlue: string,
  icspRqstDdayDt: string,
  trfEvetOccrYn: string,
  rqstAbleYn: string,
  rqstUnableRsn: string,
  icspRqstKdCd: string,
  icspRqstUpldSped: string,
  icspRqstDownSped: string,
  bizEmpNm: string,
  bizEmpHpno: string,
  bizEmpEmalAddr: string,
}

